version: '2'
services:
  api:
        build: ./api
        volumes:
            - ./api:/api
            - /api/node_modules
        ports:
            - 3000:3000
        depends_on:
            - mysql      
  mysql:
        container_name: mysql
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'clase'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        expose:
        - '3306'
   
  phpmyadmin:
        image: phpmyadmin
        depends_on:
            - "mysql"
        links:
            - "mysql"
        ports:
            - 8080:80  
        environment: 
            PMA_HOST: 'mysql'
            PMA_USER: 'root'
            PMA_PASSWORD: 'password'
